### ISSUE TITLE
Slides index page

### ISSUE THREAD

**Issue by brian-yu** [markfloryan/pdr#48]
>Slide set 5: Trees (version from Reiss's lectures (PDF))
>>The trees diagrams were generated from the files described here
>>The tree animation site is here (mirror)

AVL tree animation links are broken/java applets don't work on newer browsers.
Maybe add this link instead?
https://www.cs.usfca.edu/~galles/visualization/AVLtree.html

**Comment by smasher164** [comment]
Since this link was used last semester to demonstrate rotations to the class. I agree that this should replace the applet in the slides.

Wanna send a pull request?

**Comment by brian-yu** [comment]
@smasher164 Yep, totally. Should I just edit the markdown file/are the html files automatically generated?

**Comment by markfloryan** [comment]
I merged your pull request.
